# -*- coding: utf-8 -*-
"""first_py_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QtwWQKUU9ZsyXOuP6MjyeQffcvZxFLzJ
"""

import streamlit as st
# To make things easier later, we're also importing numpy and pandas for
# working with sample data.
import numpy as np
import pandas as pd

# import new data
from google.colab import files
uploaded = files.upload()
data = pd.read_csv("insurance.csv", delimiter = ",")
data.head()



# Run xgboost model